language: ru

pipeline:
- name: WhitespaceTokenizer                  # Токенизатор, разделяющий текст по пробелам
- name: RegexFeaturizer                      # Извлечение признаков с помощью регулярных выражений
- name: LexicalSyntacticFeaturizer           # Лексико-синтаксический анализатор
- name: CountVectorsFeaturizer               # Извлечение признаков по частоте слов
  analyzer: "char_wb"                        # Символьные N-граммы
  min_ngram: 1
  max_ngram: 4                               # Уменьшены размеры N-грамм для ускорения

  # Подключение предобученной модели трансформера (BERT)
- name: "LanguageModelFeaturizer"
  model_name: "bert"                         # Модель BERT для русского языка
  model_weights: "bert-base-cased"            # Весы модели BERT
  cache_dir: null

- name: DIETClassifier                        # Классификатор на базе DIET
  epochs: 100                                   # Минимальное количество эпох обучения
  transformer_size: 32                        # Минимальный размер слоя трансформера
  number_of_transformer_layers: 1             # Один слой трансформера
  use_masked_language_model: false            # Отключено для ускорения
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [32]                                # Минимальные скрытые слои

- name: EntitySynonymMapper                   # Маппер синонимов сущностей
- name: ResponseSelector                      # Минимальный выбор ответа
  epochs: 1                                   # Минимальное количество эпох обучения

policies:
- name: MemoizationPolicy
  max_history: 2                            # Минимальная история
- name: RulePolicy
- name: TEDPolicy
  max_history: 2                            # Минимальное количество шагов в истории
  epochs: 1                                 # Минимальное количество эпох обучения
  constrain_similarities: true
assistant_id: 20240922-215607-brilliant-synth
